application: hackcooper-nocontext
version: 0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico


- url: /static/css
  static_dir: static/css/

- url: /static/js/
  static_dir: static/js/

- url: /.*
  script: app.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
