application: freezing-hipster
version: 0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: app.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
